apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm
  namespace: kafka-enterprise
data:
  realm-export.json: |
    {
      "realm": "enterprise-kafka",
      "enabled": true,
      "roles": {
        "realm": [
          { "name": "Kafka_Admins" },
          { "name": "Equities_Team" },
          { "name": "FI_Team" }
        ]
      },
      "groups": [
        { "name": "Kafka_Admins" },
        { "name": "Equities_Team" },
        { "name": "FI_Team" }
      ],
      "users": [
        {
          "username": "admin",
          "enabled": true,
          "credentials": [{ "type": "password", "value": "admin123" }],
          "groups": ["Kafka_Admins"]
        },
        {
          "username": "equities-user",
          "enabled": true,
          "credentials": [{ "type": "password", "value": "equities123" }],
          "groups": ["Equities_Team"]
        },
        {
          "username": "fi-user",
          "enabled": true,
          "credentials": [{ "type": "password", "value": "fi123" }],
          "groups": ["FI_Team"]
        }
      ],
      "clients": [
        {
          "clientId": "kafka-ui",
          "secret": "kafka-ui-secret",
          "enabled": true,
          "publicClient": false,
          "directAccessGrantsEnabled": true,
          "redirectUris": ["*"],
          "webOrigins": ["*"],
          "protocolMappers": [
            {
              "name": "groups",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-group-membership-mapper",
              "consentRequired": false,
              "config": {
                "full.path": "false",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "claim.name": "groups",
                "userinfo.token.claim": "true"
              }
            }
          ]
        }
      ]
    }
