apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: admin
  namespace: kafka-enterprise
  labels:
    strimzi.io/cluster: enterprise-kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "*"
          patternType: literal
        operations:
          - All
      - resource:
          type: group
          name: "*"
          patternType: literal
        operations:
          - All
      - resource:
          type: cluster
        operations:
          - All
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: equities-manager
  namespace: kafka-enterprise
  labels:
    strimzi.io/cluster: enterprise-kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "equities-"
          patternType: prefix
        operations:
          - All
      - resource:
          type: group
          name: "equities-"
          patternType: prefix
        operations:
          - All
      - resource:
          type: cluster
        operations:
          - Create
          - Describe
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: equities-writer
  namespace: kafka-enterprise
  labels:
    strimzi.io/cluster: enterprise-kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "equities-"
          patternType: prefix
        operations:
          - Write
          - Describe
          - DescribeConfigs
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: equities-reader
  namespace: kafka-enterprise
  labels:
    strimzi.io/cluster: enterprise-kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "equities-"
          patternType: prefix
        operations:
          - Read
          - Describe
          - DescribeConfigs
      - resource:
          type: group
          name: "equities-"
          patternType: prefix
        operations:
          - Read
          - Describe
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: fi-manager
  namespace: kafka-enterprise
  labels:
    strimzi.io/cluster: enterprise-kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "fi-"
          patternType: prefix
        operations:
          - All
      - resource:
          type: group
          name: "fi-"
          patternType: prefix
        operations:
          - All
      - resource:
          type: cluster
        operations:
          - Create
          - Describe
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: fi-writer
  namespace: kafka-enterprise
  labels:
    strimzi.io/cluster: enterprise-kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "fi-"
          patternType: prefix
        operations:
          - Write
          - Describe
          - DescribeConfigs
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: fi-reader
  namespace: kafka-enterprise
  labels:
    strimzi.io/cluster: enterprise-kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "fi-"
          patternType: prefix
        operations:
          - Read
          - Describe
          - DescribeConfigs
      - resource:
          type: group
          name: "fi-"
          patternType: prefix
        operations:
          - Read
          - Describe
