apiVersion: v1
kind: ConfigMap
metadata:
  name: kafbat-ui-config
  namespace: kafka-enterprise
data:
  config.yml: |
    auth:
      type: LOGIN_FORM
    spring:
      security:
        user:
          name: admin
          password: admin123
